### ISSUE TITLE
Different use of word 'context' in code compared to paper?

### ISSUE THREAD

**Issue by Binbose** [CW-Huang/torchkit#4]
Hey, awesome project! 
However, do I understand it correctly, that you use the word 'context' differently in your code, compared to your paper https://arxiv.org/pdf/1804.00779.pdf
In the paper, context is a function depending on the previous dimensions, whereas in the code, it seems like context is a variable, that is set constant to 2.0 (I assume, it can be used to condition the network on some additional input, is that correct?)

**Comment by CW-Huang** [comment]
you're right: context in the code is used for conditioning. 

In the paper we also use the word "context" to describe conditioning on data in amortized inference (VAE), see Appendix H. Here's a piece of description quoted from there:
"... The convolution layers are followed by a fully connected layer of size 450 as a context for
the flow layers that transform the noise sampled from a standard normal distribution of dimension 32. ..."

**Comment by Binbose** [comment]
Ah sorry, I mixed it up with conditioner, I should have been more careful.
Thank you though!
